config/routes.rb
Assetcorrelation::Application.routes.draw do

  resources :subscriptions

  resources :plans

  devise_for :users
  
  resources :users, :only => :show
  resources :macrovals
  resources :positions
  resources :price_quotes
  resources :securities
  resources :portfolios

  authenticated :user do
    root 'portfolios#index', as: :authenticated_root
  end
  root "home#index"

	mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get '/majors/(:id)'        => 'correlation#correlations',   :as => 'majors'
  get '/bonds/(:id)'			   => 'correlation#bonds',   			  :as => 'bonds'
  get '/sectors/(:id)' 			 => 'correlation#sectors',   		  :as => 'sectors'
  get '/international/(:id)' => 'correlation#countries',      :as => 'international'
  get '/custom'              => 'correlation#custom',         :as => 'custom'
  get '/time'                => 'correlation#time',           :as => 'time'
  get '/corr_over_time'      => 'correlation#corr_over_time', :as => 'corr_over_time'

	get '/primer'              => 'info#primer',							  :as => 'primer'
	get '/support'				     => 'info#support',							  :as => 'support'
	
  get '/shiller_dash'        => 'macrovals#dashboard',        :as => 'shiller_dash'
  get '/calc_shiller'        => 'macrovals#calculate_cols',   :as => 'calc_shiller'
	
	get '/valid_security'		   => 'securities#valid_security',  :as => 'valid_security'
	
	get '/account'             => 'users#show',                 :as => 'account'
  get '/user_csdl'           => 'users#custom_csdl',          :as => 'user_csdl'

  get '/payment'             => 'subscriptions#payment',      :as => 'payment'

  # old routes
  get 'user/enter_time_corr'         => 'correlation#time'
  get 'user/correlations/(:id)'      => 'correlation#correlations'
  get 'user/bonds/(:id)'             => 'correlation#bonds'
  get 'user/sectors/(:id)'           => 'correlation#sectors'
  get 'user/countries/(:id)'         => 'correlation#countries'
  get 'user/simple_asset_allocation' => 'home#index'   # page no longer exists


end

app/models/position.rb
class Position < ActiveRecord::Base

  belongs_to :security
  
  accepts_nested_attributes_for :security

end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController

  before_action :authenticate_user!  
  
  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @positions }
    end
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
    @position = Position.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/new
  # GET /positions/new.json
  def new
    @position = Position.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/1/edit
  def edit
    @position = Position.find(params[:id])
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new( position_params )

    respond_to do |format|
      if @position.save
        format.html { redirect_to portfolio_path(@position.portfolio_id), notice: 'Position was successfully created.' }
        format.json { render json: @position, status: :created, location: @position }
      else
        format.html { render action: "new" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /positions/1
  # PUT /positions/1.json
  def update
    @position = Position.find(params[:id])

    respond_to do |format|
      if @position.update( position_params )
        format.html { redirect_to portfolio_path(@position.portfolio_id), notice: 'Position was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    respond_to do |format|
      format.json { render :json => {:msg => 'Position deleted' }, :status => :ok }
      format.html { redirect_to positions_url }
    end
  end

  private

  def position_params
    params.require(:position).permit(:shares, :portfolio_id, :security_id, 
                                     securities_attributes: [:id, :name, :ticker, :asset_class])
  end

end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :security_id %><br />
    <%= f.number_field :security_id %>
  </div>
  
  
  <div class="field">
    <%= f.label :holding_percentage %><br />
    <%= f.text_field :holding_percentage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing position</h1>

<%= render 'form' %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<h1>Listing positions</h1>

<table>
  <tr>
    <th>Asset</th>
    <th>Holding percentage</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @positions.each do |position| %>
  <tr>
    <td><%= position.security_id %></td>
    <td><%= position.holding_percentage %></td>
    <td><%= link_to 'Show', position %></td>
    <td><%= link_to 'Edit', edit_position_path(position) %></td>
    <td><%= link_to 'Destroy', position, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New position</h1>

<%= render 'form' %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Asset:</b>
  <%= @position.security.name %> [ <%= @position.security.ticker %>]
</p>

<p>
  <b>Holding percentage:</b>
  <%= @position.holding_percentage %>
</p>


<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>