config/routes.rb
Assetcorrelation::Application.routes.draw do

  resources :subscriptions

  resources :plans

  devise_for :users
  
  resources :users, :only => :show
  resources :macrovals
  resources :positions
  resources :price_quotes
  resources :securities
  resources :portfolios

  authenticated :user do
    root 'portfolios#index', as: :authenticated_root
  end
  root "home#index"

	mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get '/majors/(:id)'        => 'correlation#correlations',   :as => 'majors'
  get '/bonds/(:id)'			   => 'correlation#bonds',   			  :as => 'bonds'
  get '/sectors/(:id)' 			 => 'correlation#sectors',   		  :as => 'sectors'
  get '/international/(:id)' => 'correlation#countries',      :as => 'international'
  get '/custom'              => 'correlation#custom',         :as => 'custom'
  get '/time'                => 'correlation#time',           :as => 'time'
  get '/corr_over_time'      => 'correlation#corr_over_time', :as => 'corr_over_time'

	get '/primer'              => 'info#primer',							  :as => 'primer'
	get '/support'				     => 'info#support',							  :as => 'support'
	
  get '/shiller_dash'        => 'macrovals#dashboard',        :as => 'shiller_dash'
  get '/calc_shiller'        => 'macrovals#calculate_cols',   :as => 'calc_shiller'
	
	get '/valid_security'		   => 'securities#valid_security',  :as => 'valid_security'
	
	get '/account'             => 'users#show',                 :as => 'account'
  get '/user_csdl'           => 'users#custom_csdl',          :as => 'user_csdl'

  get '/payment'             => 'subscriptions#payment',      :as => 'payment'

  # old routes
  get 'user/enter_time_corr'         => 'correlation#time'
  get 'user/correlations/(:id)'      => 'correlation#correlations'
  get 'user/bonds/(:id)'             => 'correlation#bonds'
  get 'user/sectors/(:id)'           => 'correlation#sectors'
  get 'user/countries/(:id)'         => 'correlation#countries'
  get 'user/simple_asset_allocation' => 'home#index'   # page no longer exists


end

app/controllers/macroval_controller.rb
# To do list
# ~~~~~~~~~~

# Change log
# ~~~~~~~~~~


class MacrovalController < ApplicationController

  def index
    
  end
 
  # ----------------------------------------------------------------------------------------------------------
  # Show Entire Database
  # Inputs:   
  # Outputs:  
  # ----------------------------------------------------------------------------------------------------------  
  def show_db
    @db = Macroval.all
  end
  
  # ----------------------------------------------------------------------------------------------------------
  # Main Dashboard
  # Inputs:   
  # Outputs:  
  # ----------------------------------------------------------------------------------------------------------  
  def dashboard
    
    
    equity_risk_yield_ranges  = [-5, -2, 0, 2, 4, 6, 9, 16] # min = -4.38, max = 14.88
    pe_ten_year_ranges        = [4, 10, 15, 20, 25, 30, 35, 45] # min = 4.78, max = 44.2
    
    # ===== Get today's S&P500 price ====

    
    
    # ===== Equity Risk Yield Table =====
    @equity_risk_yield_table = Array.new
    @equity_risk_yield_headings = ['Range', 'Return', 'Months']
    
    for i in 0...equity_risk_yield_ranges.size-1
      
      range_start = equity_risk_yield_ranges[i]
      range_end   = equity_risk_yield_ranges[i+1]

      logger.debug("*** Querying database for equity risk yield values in range: #{range_start..range_end}")
      dataset     = Macroval.find_equity_risk_yield(range_start..range_end)
      logger.debug("*** Retrieved #{dataset.size} records")
      
      table_row             = Hash.new
      table_row[:range]     = range_start.to_s + " - " + range_end.to_s
      table_row[:mo_ret]    = 100 * (dataset.collect(&:monthly_return).collect(&:to_f).collect { |r| 1 + r/100 }.geometric_mean - 1)
      table_row[:mo_count]  = dataset.size
      
      @equity_risk_yield_table << table_row
      
    end
    
    # ===== PE Table =====
    @pe_ten_year_table = Array.new
    @pe_ten_year_headings = ['Range', 'Return', 'Months']
    
    for i in 0...pe_ten_year_ranges.size-1
      
      range_start = pe_ten_year_ranges[i]
      range_end   = pe_ten_year_ranges[i+1]

      dataset     = Macroval.find_pe(range_start..range_end)
      
      table_row             = Hash.new
      table_row[:range]     = range_start.to_s + " - " + range_end.to_s
      table_row[:mo_ret]    = 100 * (dataset.collect(&:monthly_return).collect(&:to_f).collect { |r| 1 + r/100 }.geometric_mean - 1)
      table_row[:mo_count]  = dataset.size
      
      @pe_ten_year_table << table_row
      
    end   
  end
  
  
  # ----------------------------------------------------------------------------------------------------------
  # Generate all calculated columns - long latency
  # Inputs:   
  # Outputs:  
  # ----------------------------------------------------------------------------------------------------------  
  def calculate_cols
    Macroval.calculate_all_columns
    redirect_to :action => :dashboard
  end
  
  
  # ----------------------------------------------------------------------------------------------------------
  # Interactive Database Filter
  # Inputs:   
  # Outputs:  
  # ----------------------------------------------------------------------------------------------------------  
  def interactive
    @db = Macroval.all(:limit => 10)
  end  
  
  # ----------------------------------------------------------------------------------------------------------
  # Interactive Database Filter
  # Inputs:   
  # Outputs:  
  # ----------------------------------------------------------------------------------------------------------  
  def filter_db
    
    start         = params[:start]
    finish        = params[:finish]
    search_field  = params[:search_on][:field]
    sort_field    = search_field == "year_month" ? "pe_tenyear" : search_field
    
    @db = Macroval.find(:all, :conditions => {"#{search_field}" => start..finish}, :limit => 24, :order => "#{sort_field} ASC")
    
    render :partial => 'macroval', :layout=>false 
  end  
  
  # ----------------------------------------------------------------------------------------------------------
  # Add recent Shiller data
  # Inputs:   
  # Outputs:  
  # ----------------------------------------------------------------------------------------------------------  
  def add_latest_data
    @db =  Macroval.find_year_month(2009..2020)
  end  
  
  # ----------------------------------------------------------------------------------------------------------
  # Add recent Shiller data
  # Inputs:   
  # Outputs:  
  # ----------------------------------------------------------------------------------------------------------  
  def add_month_to_db
    
    year, month = Macroval.most_recent_month
    
    logger.info("*** Latest data in DB is for year #{year} and month #{month}")
       
       
    new_month = (month == 12) ? 1       : month+1
    new_year  = (month == 12) ? year+1  : year
    
    logger.info("*** Trying to add new data for year #{new_year} and month #{new_month}")
    
    Macroval.create( :year_month => new_year+new_month.to_f/100 )
    
    logger.info("*** New month added to dataset.")
    logger.info("Last month is: #{Macroval.last.year_month}")    
        
    redirect_to :action => 'add_latest_data'
    
  end    
  
  # ----------------------------------------------------------------------------------------------------------
  # In place editing support
  # ----------------------------------------------------------------------------------------------------------    
  def update_month
    month_id, field = params[:id].split('-')
    new_data        = params[:value] # need to clean this up with hpricot or equivalent

    @month    = Macroval.find(month_id)
    
    # http://stackoverflow.com/questions/300705/variables-in-ruby-method-names
    @month.send("#{field}=".to_sym, new_data)

    @month.save
    render :text => new_data
  end    
  
end

app/controllers/macrovals_controller.rb
class MacrovalsController < ApplicationController
  
  before_action :authenticate_user!
  before_action :authorize, :except => [:dashboard, :index]
    
  # GET /macrovals
  # GET /macrovals.json
  def index
 
    @tab = "macro" 
    @sub = "db"   
 
    @macrovals = Macroval.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @macrovals }
    end
  end

  # GET /macrovals/1
  # GET /macrovals/1.json
  def show
    @macroval = Macroval.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @macroval }
    end
  end

  # GET /macrovals/new
  # GET /macrovals/new.json
  def new
    @macroval = Macroval.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @macroval }
    end
  end

  # GET /macrovals/1/edit
  def edit
    @macroval = Macroval.find(params[:id])
  end

  # POST /macrovals
  # POST /macrovals.json
  def create
    @macroval = Macroval.new(params[:macroval])

    respond_to do |format|
      if @macroval.save
        format.html { redirect_to @macroval, notice: 'Macroval was successfully created.' }
        format.json { render json: @macroval, status: :created, location: @macroval }
      else
        format.html { render action: "new" }
        format.json { render json: @macroval.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /macrovals/1
  # PUT /macrovals/1.json
  def update
    @macroval = Macroval.find(params[:id])

    respond_to do |format|
      if @macroval.update_attributes(params[:macroval])
        format.html { redirect_to @macroval, notice: 'Macroval was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @macroval.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /macrovals/1
  # DELETE /macrovals/1.json
  def destroy
    @macroval = Macroval.find(params[:id])
    @macroval.destroy

    respond_to do |format|
      format.html { redirect_to macrovals_url }
      format.json { head :ok }
    end
  end
  
  #------------- ^^ Scaffolding above this line ^^ --------------------------------------------------------
  
  
  # ----------------------------------------------------------------------------------------------------------
  # Show Entire Database
  # Inputs:   
  # Outputs:  
  # ----------------------------------------------------------------------------------------------------------  
  def show_db
  	
    @tab = "macro" 
    @sub = "db"   	
  	
    @db = Macroval.all
  end
  
  # ----------------------------------------------------------------------------------------------------------
  # Main Dashboard
  # Inputs:   
  # Outputs:  
  # ----------------------------------------------------------------------------------------------------------  
  def dashboard
 
    @tab = "macro" 
    @sub = "dash"   
    
    
    equity_risk_yield_ranges  = [-5, -2, 0, 2, 4, 6, 9, 16] # min = -4.38, max = 14.88
    pe_ten_year_ranges        = [4, 10, 15, 20, 25, 30, 35, 45] # min = 4.78, max = 44.2
    
    # ===== Calculate today's Shiller 10 Yr PE Ratio ====

    @quote_type_a  = YahooFinance::StandardQuote
    @quote_type_b  = YahooFinance::ExtendedQuote
    @quote_type_c  = YahooFinance::RealTimeQuote

    @quote_symbols = "^TNX,^GSPC"
    
    # Get the quotes from Yahoo! Finance.  The get_quotes method call
    # returns a Hash containing one quote object of type "quote_type" for
    # each symbol in "quote_symbols".  If a block is given, it will be
    # called with the quote object (as in the example below).
    @quotes      = YahooFinance::get_quotes( @quote_type_a, @quote_symbols )
        
    # Calculate Shiller 10 Yr PE Ratio
		@ten_yr_rate = @quotes['^TNX' ].lastTrade
		@s_and_p		 = @quotes['^GSPC'].lastTrade
    @shiller_pe  = @quotes['^GSPC'].lastTrade / Macroval.last.spcomposite.to_f * Macroval.last.pe_tenyear.to_f 
		@ery				 = 1 / @shiller_pe * 100 - @ten_yr_rate
    
    # ===== Equity Risk Yield Table =====
    @equity_risk_yield_table = Array.new
    @equity_risk_yield_headings = ['Equity Risk', 'Return', 'Months']
    
    for i in 0...equity_risk_yield_ranges.size-1
      
      range_start = equity_risk_yield_ranges[i]
      range_end   = equity_risk_yield_ranges[i+1]

      dataset     = Macroval.find_equity_risk_yield(range_start..range_end)
            
      table_row             = Hash.new
      table_row[:range]     = range_start.to_s + " - " + range_end.to_s
      table_row[:mo_ret]    = 100 * (dataset.collect(&:monthly_return).collect(&:to_f).collect { |r| 1 + r/100 }.geometric_mean - 1)
      table_row[:mo_count]  = dataset.size
      
      @equity_risk_yield_table << table_row
      
    end
    
    # ===== PE Table =====
    @pe_ten_year_table = Array.new
    @pe_ten_year_headings = ['10 Yr P/E', 'Return', 'Months']
    
    for i in 0...pe_ten_year_ranges.size-1
      
      range_start = pe_ten_year_ranges[i]
      range_end   = pe_ten_year_ranges[i+1]

      dataset     = Macroval.find_pe(range_start..range_end)
      
      table_row             = Hash.new
      table_row[:range]     = range_start.to_s + " - " + range_end.to_s
      table_row[:mo_ret]    = 100 * (dataset.collect(&:monthly_return).collect(&:to_f).collect { |r| 1 + r/100 }.geometric_mean - 1)
      table_row[:mo_count]  = dataset.size
      
      @pe_ten_year_table << table_row
      
    end   
  end
  
  
  # ----------------------------------------------------------------------------------------------------------
  # Generate all calculated columns - long latency
  # Inputs:   
  # Outputs:  
  # ----------------------------------------------------------------------------------------------------------  
  def calculate_cols
    Macroval.calculate_all_columns
    redirect_to :action => :dashboard
  end
  
  
  # ----------------------------------------------------------------------------------------------------------
  # Interactive Database Filter
  # Inputs:   
  # Outputs:  
  # ----------------------------------------------------------------------------------------------------------  
  def interactive
    @db = Macroval.all(:limit => 10)
  end  
  
  # ----------------------------------------------------------------------------------------------------------
  # Interactive Database Filter
  # Inputs:   
  # Outputs:  
  # ----------------------------------------------------------------------------------------------------------  
  def filter_db
    
    start         = params[:start]
    finish        = params[:finish]
    search_field  = params[:search_on][:field]
    sort_field    = search_field == "year_month" ? "pe_tenyear" : search_field
    
    @db = Macroval.find(:all, :conditions => {"#{search_field}" => start..finish}, :limit => 24, :order => "#{sort_field} ASC")
    
    render :partial => 'macroval', :layout=>false 
  end  
  
  # ----------------------------------------------------------------------------------------------------------
  # Add recent Shiller data
  # Inputs:   
  # Outputs:  
  # ----------------------------------------------------------------------------------------------------------  
  def add_latest_data
    @db =  Macroval.find_year_month(2010..2020)
  end  
  
  # ----------------------------------------------------------------------------------------------------------
  # Add recent Shiller data
  # Inputs:   
  # Outputs:  
  # ----------------------------------------------------------------------------------------------------------  
  def add_month_to_db
    
    year, month = Macroval.most_recent_month       
       
    new_month = (month == 12) ? 1       : month+1
    new_year  = (month == 12) ? year+1  : year
        
    Macroval.create( :year_month => new_year+new_month.to_f/100 )  
        
    redirect_to :action => 'add_latest_data'
    
  end    
  
  # ----------------------------------------------------------------------------------------------------------
  # In place editing support
  # ----------------------------------------------------------------------------------------------------------    
  def update_month
    month_id, field = params[:id].split('-')
    new_data        = params[:value] # need to clean this up with hpricot or equivalent

    @month    = Macroval.find(month_id)
    
    # http://stackoverflow.com/questions/300705/variables-in-ruby-method-names
    @month.send("#{field}=".to_sym, new_data)

    @month.save
    render :text => new_data
  end    
  
  
  
end

app/helpers/macrovals_helper.rb
module MacrovalsHelper
end

app/views/macrovals/_form.html.erb
<%= simple_form_for(@macroval) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :year_month %>
    <%= f.input :spcomposite %>
    <%= f.input :dividends %>
    <%= f.input :earnings %>
    <%= f.input :cpi %>
    <%= f.input :date_fraction %>
    <%= f.input :ten_year_rate %>
    <%= f.input :price_real %>
    <%= f.input :dividends_real %>
    <%= f.input :earnings_real %>
    <%= f.input :pe_tenyear %>
    <%= f.input :monthly_return %>
    <%= f.input :one_year_return %>
    <%= f.input :three_year_return %>
    <%= f.input :equity_risk_yield %>
    <%= f.input :dividend_yield %>
    <%= f.input :earnings_yield %>
    <%= f.input :inflation %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/macrovals/dashboard.html.erb
<h1>Expected S&P 500 Return Based on Historical P/E Ranges</h1>

<div class="macro-buckets" id="left">
	
	<div class='small-table'>
		<h3>Expected Return by 10 Yr PE</h3>
		<table class="nostradamus-standard">
			<thead>
				<tr>
				  <% for hdg in @pe_ten_year_headings %>
				  		<th><%= hdg %></th>
				  <% end %>
		  		</tr>
			</thead>
	
			<tbody>
				  <% for row in @pe_ten_year_table %>
					  <tr <%= in_range( @shiller_pe, row[:range] ) %> >
					    <td align="right"><%= row[:range]    %> x</td>
					    <td align="right"><%= number_with_precision(row[:mo_ret], :precision => 1) %> %</td>		
						<td align="right"><%= row[:mo_count] %></td>		 
					  </tr>
				  <% end %>
			</tbody>
		</table>
	</div>
	
	<div class="footnotes">	
		<h4>Notes</h4>
		<ol>
			<li>Expected return is calculated using annualized geometric mean of monthly returns</li>
			<li>Return calculation includes dividends and is adjusted for inflation</li>		
			<li>'Months' column is number of months that 10 Yr PE was in given range</li>
			<li>Shiller ten year P/E as of today is <%= number_with_precision(@shiller_pe, :precision => 1) %></li>
		</ol>
	</div>
</div>

<div class="macro-buckets" id="right">
	<div class='small-table'>	
		<h3>Expected Return by Equity Risk Yield</h3>
		<table class="nostradamus-standard">
			<thead><tr>
			  <% for hdg in @equity_risk_yield_headings %>
			  		<th><%= hdg %></th>
			  <% end %>
		  	</tr></thead>
	
			<tbody>
				  <% for row in @equity_risk_yield_table %>
					  <tr <%= in_range( @ery, row[:range] ) %> >
					    <td align="right"><%= row[:range]    %> %</td>
					    <td align="right"><%= number_with_precision(row[:mo_ret], :precision => 1) %> %</td>		
						<td align="right"><%= row[:mo_count] %></td>		 
					  </tr>
				  <% end %>
			</tbody>
		</table>
	</div>
	
	<div class="footnotes">
		<h4>Notes</h4>
		<ol>
			<li>Expected return is calculated using annualized geometric mean of monthly returns</li>
			<li>Return calculation includes dividends and is adjusted for inflation</li>
			<li>Equity risk yield is calculated as (1 / 10 Yr PE) - 10 Yr Treasury Rate</li>
			<li>'Months' column is number of months that equity risk yield was in given range</li>
			<li>10 Yr rate as of today is <%= number_with_precision(@ten_yr_rate, :precision => 1) %>%. The
				equity risk yield is <%= number_with_precision(@ery, :precision => 1) %>%.</li>			
		</ol>	
	</div>
	
</div>

<div class="clr"></div>

app/views/macrovals/edit.html.erb
<h1>Editing macroval</h1>

<%= render 'form' %>

<%= link_to 'Show', @macroval %> |
<%= link_to 'Back', macrovals_path %>

app/views/macrovals/index.html.erb
<h1>Shiller Price Earning Data (1871 - Present)</h1>

<table class='nostradamus-standard'>
	<thead>
		<tr>
			<th>Date</th>
			<th>S&P</th>
			<th>Div.</th>
			<th>Earn.</th>
			<th>Cpi</th>
			<th>10 Yr Rate</th>
			<th>Price (Real)</th>
			<th>Div. (Real)</th>
			<th>Earn. (Real)</th>
			<th>10 Yr P/Er</th>
			<th>Monthly Ret.</th>
			<th>Equity Risk Yield</th>
			<th>Div. Yield</th>
			<th>Earn. Yield</th>
			<th>Inflation</th>
		</tr>
	</thead>

	<tbody>
		<% @macrovals.each do |macroval| %>
		  <tr>
		    <td class="decimal"><%= number_with_precision( macroval.year_month,			:precision => 2	) %></td>
		    <td class="decimal"><%= number_with_precision( macroval.spcomposite,		:precision => 2	) %></td>
		    <td class="decimal"><%= number_with_precision( macroval.dividends,			:precision => 2	) %></td>
		    <td class="decimal"><%= number_with_precision( macroval.earnings,			:precision => 2	) %></td>
		    <td class="decimal"><%= number_with_precision( macroval.cpi,				:precision => 1	) %></td>
		    <td class="decimal"><%= number_with_precision( macroval.ten_year_rate,		:precision => 2	) %></td>
		    <td class="decimal"><%= number_with_precision( macroval.price_real,			:precision => 1	) %></td>
		    <td class="decimal"><%= number_with_precision( macroval.dividends_real,		:precision => 1 ) %></td>
		    <td class="decimal"><%= number_with_precision( macroval.earnings_real,		:precision => 1 ) %></td>
		    <td class="decimal"><%= number_with_precision( macroval.pe_tenyear, 		:precision => 1 ) %></td>
		    <td class="decimal"><%= number_with_precision( macroval.monthly_return, 	:precision => 1 ) %></td>
		    <td class="decimal"><%= number_with_precision( macroval.equity_risk_yield,	:precision => 1	) %></td>
		    <td class="decimal"><%= number_with_precision( macroval.dividend_yield,		:precision => 1	) %></td>
		    <td class="decimal"><%= number_with_precision( macroval.earnings_yield,		:precision => 1	) %></td>
		    <td class="decimal"><%= number_with_precision( macroval.inflation,			:precision => 1	) %></td>
		  </tr>
		<% end %>	
	</tbody>

</table>

<br />

<% if current_user && current_user.admin? %>
	<%= link_to 'New Macroval', new_macroval_path %>
<% end %>

app/views/macrovals/new.html.erb
<h1>New macroval</h1>

<%= render 'form' %>

<%= link_to 'Back', macrovals_path %>

app/views/macrovals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Year month:</b>
  <%= @macroval.year_month %>
</p>

<p>
  <b>Spcomposite:</b>
  <%= @macroval.spcomposite %>
</p>

<p>
  <b>Dividends:</b>
  <%= @macroval.dividends %>
</p>

<p>
  <b>Earnings:</b>
  <%= @macroval.earnings %>
</p>

<p>
  <b>Cpi:</b>
  <%= @macroval.cpi %>
</p>

<p>
  <b>Date fraction:</b>
  <%= @macroval.date_fraction %>
</p>

<p>
  <b>Ten year rate:</b>
  <%= @macroval.ten_year_rate %>
</p>

<p>
  <b>Price real:</b>
  <%= @macroval.price_real %>
</p>

<p>
  <b>Dividends real:</b>
  <%= @macroval.dividends_real %>
</p>

<p>
  <b>Earnings real:</b>
  <%= @macroval.earnings_real %>
</p>

<p>
  <b>Pe tenyear:</b>
  <%= @macroval.pe_tenyear %>
</p>

<p>
  <b>Monthly return:</b>
  <%= @macroval.monthly_return %>
</p>

<p>
  <b>One year return:</b>
  <%= @macroval.one_year_return %>
</p>

<p>
  <b>Three year return:</b>
  <%= @macroval.three_year_return %>
</p>

<p>
  <b>Equity risk yield:</b>
  <%= @macroval.equity_risk_yield %>
</p>

<p>
  <b>Dividend yield:</b>
  <%= @macroval.dividend_yield %>
</p>

<p>
  <b>Earnings yield:</b>
  <%= @macroval.earnings_yield %>
</p>

<p>
  <b>Inflation:</b>
  <%= @macroval.inflation %>
</p>


<%= link_to 'Edit', edit_macroval_path(@macroval) %> |
<%= link_to 'Back', macrovals_path %>